# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('note', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField()),
            ],
        ),
    ]
