# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-17 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
